/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as GlobalConfigureRouteImport } from './routes/global-configure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesNameRouteImport } from './routes/templates/$name'
import { Route as TranscriptTicketTicketIdRouteImport } from './routes/transcript/ticket.$ticketId'
import { Route as ProjectsProjectIdConfigureRouteImport } from './routes/projects/$projectId/configure'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects/$projectId/board'
import { Route as ProjectsProjectIdWorkflowsWorkflowIdSettingsRouteImport } from './routes/projects/$projectId/workflows/$workflowId/settings'
import { Route as ProjectsProjectIdWorkflowsWorkflowIdBoardRouteImport } from './routes/projects/$projectId/workflows/$workflowId/board'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalConfigureRoute = GlobalConfigureRouteImport.update({
  id: '/global-configure',
  path: '/global-configure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNameRoute = TemplatesNameRouteImport.update({
  id: '/templates/$name',
  path: '/templates/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptTicketTicketIdRoute =
  TranscriptTicketTicketIdRouteImport.update({
    id: '/transcript/ticket/$ticketId',
    path: '/transcript/ticket/$ticketId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdConfigureRoute =
  ProjectsProjectIdConfigureRouteImport.update({
    id: '/projects/$projectId/configure',
    path: '/projects/$projectId/configure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/projects/$projectId/board',
  path: '/projects/$projectId/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute =
  ProjectsProjectIdWorkflowsWorkflowIdSettingsRouteImport.update({
    id: '/projects/$projectId/workflows/$workflowId/settings',
    path: '/projects/$projectId/workflows/$workflowId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdWorkflowsWorkflowIdBoardRoute =
  ProjectsProjectIdWorkflowsWorkflowIdBoardRouteImport.update({
    id: '/projects/$projectId/workflows/$workflowId/board',
    path: '/projects/$projectId/workflows/$workflowId/board',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/global-configure': typeof GlobalConfigureRoute
  '/logs': typeof LogsRoute
  '/sessions': typeof SessionsRoute
  '/templates/$name': typeof TemplatesNameRoute
  '/templates/': typeof TemplatesIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/configure': typeof ProjectsProjectIdConfigureRoute
  '/transcript/ticket/$ticketId': typeof TranscriptTicketTicketIdRoute
  '/projects/$projectId/workflows/$workflowId/board': typeof ProjectsProjectIdWorkflowsWorkflowIdBoardRoute
  '/projects/$projectId/workflows/$workflowId/settings': typeof ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/global-configure': typeof GlobalConfigureRoute
  '/logs': typeof LogsRoute
  '/sessions': typeof SessionsRoute
  '/templates/$name': typeof TemplatesNameRoute
  '/templates': typeof TemplatesIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/configure': typeof ProjectsProjectIdConfigureRoute
  '/transcript/ticket/$ticketId': typeof TranscriptTicketTicketIdRoute
  '/projects/$projectId/workflows/$workflowId/board': typeof ProjectsProjectIdWorkflowsWorkflowIdBoardRoute
  '/projects/$projectId/workflows/$workflowId/settings': typeof ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/global-configure': typeof GlobalConfigureRoute
  '/logs': typeof LogsRoute
  '/sessions': typeof SessionsRoute
  '/templates/$name': typeof TemplatesNameRoute
  '/templates/': typeof TemplatesIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/configure': typeof ProjectsProjectIdConfigureRoute
  '/transcript/ticket/$ticketId': typeof TranscriptTicketTicketIdRoute
  '/projects/$projectId/workflows/$workflowId/board': typeof ProjectsProjectIdWorkflowsWorkflowIdBoardRoute
  '/projects/$projectId/workflows/$workflowId/settings': typeof ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/global-configure'
    | '/logs'
    | '/sessions'
    | '/templates/$name'
    | '/templates/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/configure'
    | '/transcript/ticket/$ticketId'
    | '/projects/$projectId/workflows/$workflowId/board'
    | '/projects/$projectId/workflows/$workflowId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/global-configure'
    | '/logs'
    | '/sessions'
    | '/templates/$name'
    | '/templates'
    | '/projects/$projectId/board'
    | '/projects/$projectId/configure'
    | '/transcript/ticket/$ticketId'
    | '/projects/$projectId/workflows/$workflowId/board'
    | '/projects/$projectId/workflows/$workflowId/settings'
  id:
    | '__root__'
    | '/'
    | '/global-configure'
    | '/logs'
    | '/sessions'
    | '/templates/$name'
    | '/templates/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/configure'
    | '/transcript/ticket/$ticketId'
    | '/projects/$projectId/workflows/$workflowId/board'
    | '/projects/$projectId/workflows/$workflowId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlobalConfigureRoute: typeof GlobalConfigureRoute
  LogsRoute: typeof LogsRoute
  SessionsRoute: typeof SessionsRoute
  TemplatesNameRoute: typeof TemplatesNameRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdConfigureRoute: typeof ProjectsProjectIdConfigureRoute
  TranscriptTicketTicketIdRoute: typeof TranscriptTicketTicketIdRoute
  ProjectsProjectIdWorkflowsWorkflowIdBoardRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdBoardRoute
  ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-configure': {
      id: '/global-configure'
      path: '/global-configure'
      fullPath: '/global-configure'
      preLoaderRoute: typeof GlobalConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$name': {
      id: '/templates/$name'
      path: '/templates/$name'
      fullPath: '/templates/$name'
      preLoaderRoute: typeof TemplatesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript/ticket/$ticketId': {
      id: '/transcript/ticket/$ticketId'
      path: '/transcript/ticket/$ticketId'
      fullPath: '/transcript/ticket/$ticketId'
      preLoaderRoute: typeof TranscriptTicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/configure': {
      id: '/projects/$projectId/configure'
      path: '/projects/$projectId/configure'
      fullPath: '/projects/$projectId/configure'
      preLoaderRoute: typeof ProjectsProjectIdConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/projects/$projectId/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/workflows/$workflowId/settings': {
      id: '/projects/$projectId/workflows/$workflowId/settings'
      path: '/projects/$projectId/workflows/$workflowId/settings'
      fullPath: '/projects/$projectId/workflows/$workflowId/settings'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/workflows/$workflowId/board': {
      id: '/projects/$projectId/workflows/$workflowId/board'
      path: '/projects/$projectId/workflows/$workflowId/board'
      fullPath: '/projects/$projectId/workflows/$workflowId/board'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlobalConfigureRoute: GlobalConfigureRoute,
  LogsRoute: LogsRoute,
  SessionsRoute: SessionsRoute,
  TemplatesNameRoute: TemplatesNameRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdConfigureRoute: ProjectsProjectIdConfigureRoute,
  TranscriptTicketTicketIdRoute: TranscriptTicketTicketIdRoute,
  ProjectsProjectIdWorkflowsWorkflowIdBoardRoute:
    ProjectsProjectIdWorkflowsWorkflowIdBoardRoute,
  ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute:
    ProjectsProjectIdWorkflowsWorkflowIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
